// Deterministically regenerates the checker structural-depth conformance
// suite. The committed fixture is concrete deep JSON (the format has no
// depth-expression mini-language), written minified and excluded from
// spec-case formatting like the parse depth suite.

import { writeFileSync } from "fs";
import { join } from "path";
import type { JSONType } from "../src/types";

const fixturePath = join(import.meta.dir, "../../spec/cases/check/limits/structural-depth.json");
const MAX_DEPTH = 512;
const DEPTH_ERROR = `Maximum structural depth of ${MAX_DEPTH} exceeded`;

const suite = {
  $schema: "../../check.schema.json",
  description: "fixed limits: structural depth",
  comment:
    "Generated by typescript/scripts/generate-check-depth-cases.ts; regenerate instead of editing by hand.",
  builtins: "none",
  cases: [
    {
      description: "expressions nested exactly to the limit are accepted",
      expression: nestedArray(MAX_DEPTH),
      expected: { diagnostics: [] },
    },
    {
      description: "expressions nested one past the limit throw",
      expression: nestedArray(MAX_DEPTH + 1),
      throws: { messageIncludes: DEPTH_ERROR },
    },
    {
      description: "modules containing a tree past the limit throw",
      module: {
        main: {
          $params: [],
          $sig: { required: [], optional: [], returns: true },
          $return: nestedArray(MAX_DEPTH + 1),
        },
      },
      throws: { messageIncludes: DEPTH_ERROR },
    },
  ],
};

writeFileSync(fixturePath, `${JSON.stringify(suite)}\n`);

function nestedArray(depth: number, leaf: JSONType = 1): JSONType {
  let value = leaf;
  for (let index = 0; index < depth; index++) value = [value];
  return value;
}
