import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

type BuiltinDocEntry = {
  name: string;
  description: string;
};

const root = fileURLToPath(new URL("../..", import.meta.url));
const inputPath = join(root, "spec/builtins.json");
const outputPath = join(root, "docs/builtins.md");
const categoryTitles: Record<string, string> = {
  "type-checking": "Type Checking",
  coercion: "Type Coercion",
  "higher-order": "Higher-Order Functions",
  "tasks-effects": "Tasks & Effects",
};

function readMetadata(value: unknown): Map<string, BuiltinDocEntry[]> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error("Expected the builtin table to be an object");
  }

  const builtins = Reflect.get(value, "builtins");
  if (typeof builtins !== "object" || builtins === null || Array.isArray(builtins)) {
    throw new Error("Expected builtins to be an object");
  }

  const categories = new Map<string, BuiltinDocEntry[]>();
  for (const [name, value] of Object.entries(builtins)) {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      throw new Error(`Expected builtin ${name} to be an object`);
    }

    const description = Reflect.get(value, "description");
    const category = Reflect.get(value, "category");
    if (typeof description !== "string" || description.length === 0) {
      throw new Error(`Expected builtin ${name} to have a non-empty description`);
    }
    if (typeof category !== "string" || category.length === 0) {
      throw new Error(`Expected builtin ${name} to have a non-empty category`);
    }

    const entries = categories.get(category) ?? [];
    entries.push({ name, description });
    categories.set(category, entries);
  }

  return categories;
}

function titleCase(value: string): string {
  const title = categoryTitles[value];
  if (title !== undefined) return title;

  return value
    .split("-")
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join(" ");
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function renderTable(entries: BuiltinDocEntry[]): string {
  const rows = entries.map(({ name, description }) => [
    `\`${escapeCell(name)}\``,
    escapeCell(description),
  ]);
  const functionWidth = Math.max("Function".length, ...rows.map(([name]) => name!.length));
  const descriptionWidth = Math.max(
    "Description".length,
    ...rows.map(([, description]) => description!.length),
  );

  return [
    `| ${"Function".padEnd(functionWidth)} | ${"Description".padEnd(descriptionWidth)} |`,
    `| ${"-".repeat(functionWidth)} | ${"-".repeat(descriptionWidth)} |`,
    ...rows.map(
      ([name, description]) =>
        `| ${name!.padEnd(functionWidth)} | ${description!.padEnd(descriptionWidth)} |`,
    ),
  ].join("\n");
}

const source = JSON.parse(await readFile(inputPath, "utf8")) as unknown;
const categories = readMetadata(source);
const sections = [...categories].map(
  ([category, entries]) => `## ${titleCase(category)}\n\n${renderTable(entries)}`,
);
const document = `# Builtins

<!-- Generated by typescript/scripts/generate-builtin-doc.ts. Do not edit directly. -->

This reference is generated from the descriptions and categories in
[\`spec/builtins.json\`](../spec/builtins.json).

${sections.join("\n\n")}
`;

await writeFile(outputPath, document);
console.log(`Generated ${outputPath}`);
